import { Inter } from "next/font/google";
import "./globals.css";
import SplashLayout from "./components/SplashLayout";
import { ThemeProvider } from "./ThemeContext";
import { UserProvider } from "./UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ThemeProvider>
            <SplashLayout>{children}</SplashLayout>
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
