import { Inter } from "next/font/google";
import "./globals.css";
import SplashLayout from "./components/SplashLayout";
import { ThemeProvider } from "./ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <SplashLayout>{children}</SplashLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
